from django.conf.urls import patterns, include, url

from apps.sp.views.panel.Dashboard import DashboardTemplateView

urlpatterns = patterns('',
    url(r'^$',
        DashboardTemplateView.as_view(),
        name='dashboard_view'),
    url(r'^admin/', include('apps.sp.urls.panel.admin')),
    url(r'^brand/', include('apps.sp.urls.panel.brand')),
    url(r'^broadcast/', include('apps.sp.urls.panel.broadcast')),
    url(r'^studio/', include('apps.sp.urls.panel.studio')),
    url(r'^country/', include('apps.sp.urls.panel.country')),
    url(r'^commercial/', include('apps.sp.urls.panel.commercial')),
    url(r'^contract/', include('apps.sp.urls.panel.contract')),
    url(r'^model-has-commercial/', include('apps.sp.urls.panel.model_has_commercial')),
    url(r'^entry/', include('apps.sp.urls.panel.entry')),
    url(r'^model/', include('apps.sp.urls.panel.model')),
    url(r'^search/', include('apps.sp.urls.panel.search')),
    url(r'^project/', include('apps.sp.urls.panel.project')),
    url(r'^client/', include('apps.sp.urls.panel.client')),
    url(r'^casting/', include('apps.sp.urls.panel.casting')),
    url(r'^extra/', include('apps.sp.urls.panel.extra')),
    url(r'^representation/', include('apps.sp.urls.panel.representation')),
    url(r'^photo-casting/', include('apps.sp.urls.panel.photo_casting')),
    url(r'^type-casting/', include('apps.sp.urls.panel.type_casting')),
    url(r'^currency/', include('apps.sp.urls.panel.currency')),
    url(r'^employee/', include('apps.sp.urls.panel.employee')),
    url(r'^list/', include('apps.sp.urls.panel.list')),
    url(r'^pauta/', include('apps.sp.urls.panel.pauta')),
)